
import { Product } from '@/lib/schema';

export const bestSellers: Product[] = [
  {
    "id": 62,
    "name": "Terra Soya Oil (1.4L)",
    "slug": "terra-soya-oil-1-4l",
    "brand": "Terra",
    "category": "Cooking Oils & Fats",
    "categorySlug": "cooking-oils-fats",
    "imageUrl": "https://i.ibb.co/8LMKBtJ4/Terra-oil-1-4-L.png",
    "sku": "TERRA-62-OIL-1.4",
    "brandId": 30,
    "company": "TGI Group",
    "companyId": 20,
    "images": ["https://i.ibb.co/8LMKBtJ4/Terra-oil-1-4-L.png"],
    "description": "",
    "detailedDescription": "",
    "price": 0,
    "unit": "",
    "moq": 1,
    "inStock": true,
    "rating": 0,
    "isFeatured": false
  },
  {
    "id": 67,
    "name": "Terra Saver Pack",
    "slug": "terra-saver-pack",
    "brand": "Terra",
    "category": "Seasonings & Flavor",
    "categorySlug": "spices-sauces-condiments",
    "imageUrl": "https://i.ibb.co/PZvWJWzV/Terra-Saver-Pack.png",
    "sku": "TERRA-67-PACK",
    "brandId": 30,
    "company": "TGI Group",
    "companyId": 20,
    "images": ["https://i.ibb.co/PZvWJWzV/Terra-Saver-Pack.png", "https://i.ibb.co/RGSKzN89/Terra-Beef-Saver-Pack.png", "https://i.ibb.co/wts1vYN/Terra-Chicken-Super-Saver-Pack.png"],
    "description": "",
    "detailedDescription": "",
    "price": 0,
    "unit": "",
    "moq": 1,
    "inStock": true,
    "rating": 0,
    "isFeatured": false
  },
  {
    "id": 45,
    "name": "Laziz Chocolate Drink",
    "slug": "laziz-chocolate-drink",
    "brand": "Laziz",
    "category": "Snacks & Beverages",
    "categorySlug": "snacks-beverages",
    "imageUrl": "https://i.ibb.co/nqS8nkXc/Laziz-Chocolate-Drink.jpg",
    "sku": "LAZIZ-45-CHOCO",
    "brandId": 34,
    "company": "Laziz",
    "companyId": 24,
    "images": ["https://i.ibb.co/nqS8nkXc/Laziz-Chocolate-Drink.jpg"],
    "description": "",
    "detailedDescription": "",
    "price": 0,
    "unit": "",
    "moq": 1,
    "inStock": true,
    "rating": 0,
    "isFeatured": false
  },
  {
    "id": 7,
    "name": "Dangote Granulated Sugar (1kg)",
    "slug": "dangote-granulated-sugar-1kg",
    "brand": "Dangote Sugar",
    "category": "Baking & Confectionery",
    "categorySlug": "baking-confectionery",
    "imageUrl": "https://i.ibb.co/VY07nMWV/Dangote-1kg-sugar-x10.png",
    "sku": "DANGOTE-07-1KG",
    "brandId": 25,
    "company": "Dangote",
    "companyId": 4,
    "images": ["https://i.ibb.co/VY07nMWV/Dangote-1kg-sugar-x10.png"],
    "description": "",
    "detailedDescription": "",
    "price": 0,
    "unit": "",
    "moq": 1,
    "inStock": true,
    "rating": 0,
    "isFeatured": false
  },
  {
    "id": 9,
    "name": "Dano Cool Cow Milk Sachet",
    "slug": "dano-cool-cow-milk-sachet",
    "brand": "Dano",
    "category": "Dairy",
    "categorySlug": "dairy-eggs-refrigerated",
    "imageUrl": "https://i.ibb.co/ksr6PWs4/Dano-cool-cow-sachet.png",
    "sku": "DANO-09-SACHET",
    "brandId": 19,
    "company": "Arla Dano",
    "companyId": 14,
    "images": ["https://i.ibb.co/ksr6PWs4/Dano-cool-cow-sachet.png"],
    "description": "",
    "detailedDescription": "",
    "price": 0,
    "unit": "",
    "moq": 1,
    "inStock": true,
    "rating": 0,
    "isFeatured": false
  },
  {
    "id": 23,
    "name": "Golden Penny Goldenvita Wheatmeal",
    "slug": "golden-penny-wheatmeal-goldenvita",
    "brand": "Golden Penny",
    "category": "Pasta, Rice & Grains",
    "categorySlug": "pasta-rice-grains",
    "imageUrl": "https://i.ibb.co/mnhsCwf/Goldenpenny-wheatmeal-goldenvita.jpg",
    "sku": "GP-23-WHEAT",
    "brandId": 2,
    "company": "Flour Mills of Nigeria (FMN)",
    "companyId": 1,
    "images": ["https://i.ibb.co/mnhsCwf/Goldenpenny-wheatmeal-goldenvita.jpg"],
    "description": "",
    "detailedDescription": "",
    "price": 0,
    "unit": "",
    "moq": 1,
    "inStock": true,
    "rating": 0,
    "isFeatured": false
  }
];
