
ALTER TABLE products
ADD COLUMN moq INT,
ADD COLUMN unit VARCHAR(50),
ADD COLUMN rating DECIMAL(3,2),
ADD COLUMN review_count INT,
ADD COLUMN is_featured BOOLEAN DEFAULT FALSE,
ADD COLUMN tags TEXT;
